apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgresql
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: YOUR_DB
  POSTGRES_USER: YOUR_USER
  POSTGRES_PASSWORD: YOUR_PASSWORD
  PGDATA: YOUR_PGDATA_PATH