apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.64.230-192.168.64.240 # This is the range of IP addresses that MetalLB can assign to services