apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
spec:
  dnsNames:
    - YOUR_DNS_TEST_DOMAIN
  secretName: test-certificate-tls
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer